import { UniverseConfig } from '../types/universe';

export const UNIVERSES: UniverseConfig[] = [
  {
    index: 0,
    name: 'Le Prélude',
    slug: 'prelude',
    description: 'Écran noir, battement de cœur, le bouton fuit.',
    buttonComfortRadius: 300,
    buttonTrust: 0,
    buttonBehaviors: ['flee', 'feint'],
    audioLayers: ['heartbeat'],
    ambientColor: '#000000',
    transitionDuration: 3,
  },
  {
    index: 1,
    name: 'La Course-Poursuite',
    slug: 'course-poursuite',
    description: 'Nuit en ville, néons, course-poursuite GTA.',
    buttonComfortRadius: 250,
    buttonTrust: 10,
    buttonBehaviors: ['flee', 'feint'],
    audioLayers: ['ambientBase', 'reactive'],
    ambientColor: '#0a0a12',
    transitionDuration: 4,
  },
  {
    index: 2,
    name: 'YouTube',
    slug: 'youtube',
    description: 'Interface YouTube, vidéos romantiques, bouton caché.',
    buttonComfortRadius: 220,
    buttonTrust: 20,
    buttonBehaviors: ['reflection', 'flee'],
    audioLayers: ['ambientBase', 'ambientSecondary', 'reactive', 'music'],
    ambientColor: '#0f0f0f',
    transitionDuration: 4,
  },
  {
    index: 3,
    name: 'Le Jardin des Horloges',
    slug: 'jardin-horloges',
    description: 'Jardin surréaliste, fleurs mécaniques, horloges à régler.',
    buttonComfortRadius: 200,
    buttonTrust: 30,
    buttonBehaviors: ['hide', 'feint'],
    audioLayers: ['ambientBase', 'sfx', 'reactive'],
    ambientColor: '#1a0f2e',
    transitionDuration: 3.5,
  },
  {
    index: 4,
    name: 'Le Moteur de Recherche',
    slug: 'moteur-recherche',
    description: 'Interface Google, recherche romantique, puzzle en deux phases.',
    buttonComfortRadius: 180,
    buttonTrust: 40,
    buttonBehaviors: ['hide', 'hesitate'],
    audioLayers: ['ambientBase', 'ambientSecondary', 'sfx'],
    ambientColor: '#ffffff',
    transitionDuration: 3.5,
  },
  {
    index: 5,
    name: 'Netflix',
    slug: 'netflix',
    description: 'Interface Netflix, séries romantiques, bouton Play caché.',
    buttonComfortRadius: 150,
    buttonTrust: 50,
    buttonBehaviors: ['reflection', 'feint'],
    audioLayers: ['ambientBase', 'reactive', 'sfx'],
    ambientColor: '#141414',
    transitionDuration: 4,
  },
  {
    index: 6,
    name: 'Minecraft',
    slug: 'minecraft',
    description: 'Interface Minecraft, collecte d\'ingrédients, craft un cœur.',
    buttonComfortRadius: 100,
    buttonTrust: 60,
    buttonBehaviors: ['serene', 'appear'],
    audioLayers: ['ambientBase', 'music', 'reactive'],
    ambientColor: '#87CEEB',
    transitionDuration: 4,
  },
  {
    index: 7,
    name: 'Apple',
    slug: 'apple',
    description: 'Interface macOS, navigation Finder, apps interactives.',
    buttonComfortRadius: 50,
    buttonTrust: 75,
    buttonBehaviors: ['flicker', 'trustGrow'],
    audioLayers: ['ambientBase', 'ambientSecondary', 'music', 'sfx'],
    ambientColor: '#1e1e1e',
    transitionDuration: 3.5,
  },
  {
    index: 8,
    name: 'iMessage',
    slug: 'imessage',
    description: 'Interface iMessage, conversation romantique, réponse à donner.',
    buttonComfortRadius: 30,
    buttonTrust: 85,
    buttonBehaviors: ['trustGrow'],
    audioLayers: ['ambientBase', 'sfx'],
    ambientColor: '#000000',
    transitionDuration: 3,
  },
  {
    index: 9,
    name: "L'Apothéose",
    slug: 'apotheose',
    description: 'Espace doré, tous les univers convergent.',
    buttonComfortRadius: 0,
    buttonTrust: 100,
    buttonBehaviors: ['vulnerable'],
    audioLayers: ['ambientBase', 'ambientSecondary', 'music', 'sfx', 'reactive'],
    ambientColor: '#3d2e0a',
    transitionDuration: 5,
  },
];
